elements_dict = {
    "Actinium":"Ac",
    "Aluminum":"Al",
    "Americium":"Am",
    "Antimony":"Sb",
    "Argon":"Ar",
    "Arsenic":"As",
    "Astatine":"At",
    "Gold":"Au",
    "Silver":"Ag",

    "Barium":"Ba",
    "Berkelium":"Bk",
    "Beryllium":"Be",
    "Bismuth":"Bi",
    "Bohrium":"Bh",
    "Bromine":"Br",
    "Boron":"B",

    "Cadmium":"Cd",
    "Calcium":"Ca",
    "Californium":"Cf",
    "Cerium":"Ce",
    "Cesium":"Cs",
    "Chlorine":"Cl",
    "Chromium":"Cr",
    "Cobalt":"Co",
    "Copper":"Cu",
    "Curium":"Cm",
    "Carbon":"C",

    "Darmstadtium":"Ds",
    "Dubnium":"Db",
    "Dysprosium":"Dy",

    "Einsteinium":"Es",
    "Erbium":"Er",
    "Europium":"Eu",

    "Fermium":"Fm",
    "Francium":"Fr",
    "Iron":"Fe",
    "Fluorine":"F",

    "Gadolinium":"Gd",
    "Gallium":"Ga",
    "Germanium":"Ge",


    "Hafnium":"Hf",
    "Hassium":"Hs",
    "Helium":"He",
    "Holmium":"Ho",
    "Mercury":"Hg",
    "Hydrogen":"H",

    "Indium":"In",
    "Iridium":"Ir",
    "Iodine":"I",


    "Krypton":"Kr",
    "Potassium":"K",

    "Lanthanum":"La",
    "Lawrencium":"Lr",
    "Lithium":"Li",
    "Lutetium":"Lu",

    "Magnesium":"Mg",
    "Manganese":"Mn",
    "Meitnerium":"Mt",
    "Mendelevium":"Md",
    "Molybdenum":"Mo",

    "Neodymium":"Nd",
    "Sodium":"Na",
    "Neon":"Ne",
    "Neptunium":"Np",
    "Nickel":"Ni",
    "Niobium":"Nb",
    "Nobelium":"No",
    "Nitrogen":"N",

    "Osmium":"Os",
    "Oxygen":"O",

    "Palladium":"Pd",
    "Praseodymium":"Pr",
    "Promethium":"Pm",
    "Protactinium":"Pa",
    "Lead":"Pb",
    "Platinum":"Pt",
    "Plutonium":"Pu",
    "Polonium":"Po",
    "Phosphorus":"P",


    "Radium":"Ra",
    "Radon":"Rn",
    "Rhenium":"Re",
    "Rhodium":"Rh",
    "Roentgenium":"Rg",
    "Rubidium":"Rb",
    "Ruthenium":"Ru",
    "Rutherfordium":"Rf",

    "Samarium":"Sm",
    "Scandium":"Sc",
    "Seaborgium":"Sg",
    "Selenium":"Se",
    "Silicon":"Si",
    "Strontium":"Sr",
    "Tin":"Sn",
    "Sulfur":"S",

    "Tantalum":"Ta",
    "Technetium":"Tc",
    "Tellurium":"Te",
    "Terbium":"Tb",
    "Thallium":"Tl",
    "Thorium":"Th",
    "Thulium":"Tm",
    "Titanium":"Ti",
    "Total Carbon": "TC",

    "Tungsten":"W",

    "Ununbium":"Uub",
    "Ununhexium":"Uuh",
    "Ununoctium":"Uuo",
    "Ununpentium":"Uup",
    "Ununquadium":"Uuq",
    "Ununseptium":"Uus",
    "Ununtrium":"Uut",
    "Ununium":"Uuu",
    "Uranium":"U",

    "Vanadium":"V",

    "Xenon":"Xe",

    "Ytterbium":"Yb",
    "Yttrium":"Y",

    "Zinc":"Zn",
    "Zirconium":"Zr",
    "Other": "other",
    "Bal": "Balance",
    "bal": "balance",
    "RE": "Rareearthelement"
}